# Generated by Django 3.0.6 on 2021-05-22 08:16

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('register_type', models.CharField(choices=[('0', 'Admin'), ('1', 'User'), ('2', 'Merchant Manager'), ('3', 'Subordinate')], max_length=1)),
                ('menu', django.contrib.postgres.fields.jsonb.JSONField()),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pub_register', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Registration Type',
                'verbose_name_plural': 'User Registration Type',
                'ordering': ['-created'],
            },
        ),
    ]
